### PR TITLE
COMP: compile as libkahip instead of libinterface

### PR DESCRIPTION
**Pull request by olesenm**
- since this is what the depoyment script was doing anyhow, it makes
  sense to have this reflected directly within the CMakeLists so
  that either means of building will have similar results

- adjusted the compile_withcmake script accordingly

### CODE REVIEW

**Comment by schulzchristian** [comment]
thanks!

**Comment by BrushXue** [comment]
@schulzchristian Any plans to bump the version recently? The current version in homebrew still compiles `libinterface`.

**Comment by schulzchristian** [comment]
will do soon (within the next week).

**Comment by schulzchristian** [comment]
There is now a new release.

Best!
Christian

**Pull request merged**
